### ISSUE TITLE
caller_path parse error in zrequire  function 

### ISSUE THREAD

**Issue by chianquan** [bramblex/napa-loader#1]
There is a compatibility problem when parse caller_path in zrequire function.
The regex is /^\s+at\s+\S+\s+\((.+?):\d+:\d+\)$/ .But  my stack info is 

> at /Users/sucaiquan/code/qutui/api/test/napa.js:8:5'

there‘s no '()' in my stack info.
Maybe you can use the module 'callsites' to get the pure path.

在zrequire函数中有兼容性问题，我在mac   node8.2.1 的环境下 栈中的信息是不包含扣号的。应该可以通过 callsites  依赖包来获取比较原始的路径。

**Comment by bramblex** [comment]
thx, and i fixed it in https://github.com/bramblex/napa-loader/commit/136858f7ce099bf043f5d502947118dac47e51ce
